name: ebook_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^11.1.2
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  pluralize: ^0.0.8
  slugify: ^2.0.0
  fluttertoast: ^8.1.2
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  sidebarx: ^0.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
